bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: n6YCoYFU/7xpHz/y05vApNbnIyC5UXKXm+2XDWTPbrchj6bJOQ2rudimrzHFwFd5APQgu/yJYfMr7Olfr+d9Qzomup2RL4+S8AnI6/2UeW3YJHqmEffR9JhlTiVz2Zvk2ZKTcIx1wW5B6oSawV6lEQm430O+/O06Qxv4xvCEr6OHzdQaJhZeZlZTQ2ynYiMGetL8/85MkHws2ANU2DKIA3Vr7Y2F9kTc07rd0vGcUmTD7b69ssI2XYxWV06Z2rrsYyEGmKxah/A++181qAi6vvURjoa/v4+M/NyXebgo775Jpl/ZPTc2WiMTz8L6NdksETqFjO1vkYpyEgFCl5i2RoQp0J7GQKRGyCJZ1mpUh4dObwfaN+HWnpki+cHEdAsnWIzpBC7Xq5wpdNSEHPnfkQWiW1G8tJVDLDW50Uem6vYNMoX9jy9z4h8X1daS+QCXVVn2zo3fF8m3X408wE/PQBi63F4AMA9kUiNEORRNrz5hs6Ge6cUYH1pl/nNhvOinxWoS9LPVPMetCdl3hYaRRO9gTF9UE5+pJFZobkzjaphXzT5odlM6hQTA305Ih5UWAKKv00QMqMSCE9B27DzhyJF4NiD82ejRSbPhrpGLyQzp/k7GL8MvZmx47mLbLfNkGXkR6g8sCONYDKU4fnkWZ1zlJJr5fd47Q4nbv3+wAWk=
conda_forge_output_validation: true
